_# Site Settings
title: Aleksandra Zakowicz Resume
# url: 'http://webjeda.com'
baseurl: '/cv' #change it according to your repository name
about: False # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Aleksandra Zakowicz
tagline: Senior ALM Specialist
pic: 1.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: 'I am highly motivated person at the beginning of professional career. I have three years of experience in Asset and Liability Management Department. 
<br>
<br>
During this time I have learned how to ensure bank's liquidity. My main tasks cover providing effective special situations management policy, development and updating the 
Recovery Plan of Bank in accordance to local and European regulations. 
<br>
<br>
My goal is to deepen the knowledge about financial market and liquidity risk as well as combining it with analytical skills.'

#sidebar links
email: aleks.zak93@gmail.com
phone: 696 973 339
website: alezak.github.io/cv #do not add http://
linkedin: aleksandra-zakowicz
github: alezak
# twitter: '@webjeda'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
# analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
